# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand



config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")

# chargement du bv de la Vilaine
bv<-charge_shp_geogwilen(shp="bassin_vilaine", 
                     scheme="r300_territoire_sage")


# test de la fonction
pop_carroyee<-charge_shp_geogwilen(shp="filosofi2015_carreaux_200m_metropole", 
                     scheme="r350_eco_socio", 
                     shp_emprise=bv) 


test_that("charge_shp_geogwilen fonctionne sans emprise", {
  expect_true(inherits(bv, "sf"))
 expect_true(nrow(bv)>=1)
})

test_that("charge_shp_geogwilen fonctionne avec emprise", {
  expect_true(inherits(pop_carroyee, "sf"))
 expect_true(nrow(pop_carroyee)>1)
})

